// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfh2AZiyy5jYR8y3fp7tvRq6OoIx1U0yk',
    appId: '1:956244931002:web:93547d5e5b74cb492f6d83',
    messagingSenderId: '956244931002',
    projectId: 'catering-a14a9',
    authDomain: 'catering-a14a9.firebaseapp.com',
    storageBucket: 'catering-a14a9.appspot.com',
    measurementId: 'G-3KME2ZHW7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkiCrtDRAVCNgzVaan-pQWE-LhOX9tGog',
    appId: '1:956244931002:android:96f1b5cfae6a16602f6d83',
    messagingSenderId: '956244931002',
    projectId: 'catering-a14a9',
    storageBucket: 'catering-a14a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBjTugfsEc2JZnhCgkI9jaLikTkkWOuRU',
    appId: '1:956244931002:ios:e08a9e20157aac002f6d83',
    messagingSenderId: '956244931002',
    projectId: 'catering-a14a9',
    storageBucket: 'catering-a14a9.appspot.com',
    iosBundleId: 'com.example.catering',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBjTugfsEc2JZnhCgkI9jaLikTkkWOuRU',
    appId: '1:956244931002:ios:4b81be2bdbd2e6392f6d83',
    messagingSenderId: '956244931002',
    projectId: 'catering-a14a9',
    storageBucket: 'catering-a14a9.appspot.com',
    iosBundleId: 'com.example.catering.RunnerTests',
  );
}
